name: Download Latest Pre-Built Game from Live Site

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the live game folder
      run: |
        wget --mirror --page-requisites --adjust-extension --no-parent --convert-links --no-host-directories --directory-prefix=sonic4_live https://wamwoowam.co.uk/sonic4/

    - name: Upload mirrored game as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sonic4-Latest
        path: sonic4_live/
